# Generated by Django 2.0.1 on 2018-01-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('dlc', models.IntegerField(blank=True)),
                ('payload', models.CharField(blank=True, max_length=255)),
                ('puc_id', models.IntegerField(blank=True)),
                ('ts', models.DateTimeField()),
                ('gps_id', models.BigIntegerField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=14, max_digits=17)),
                ('longitude', models.DecimalField(blank=True, decimal_places=14, max_digits=17)),
                ('groundspeed', models.DecimalField(blank=True, decimal_places=14, max_digits=17)),
                ('truecourse', models.DecimalField(blank=True, decimal_places=14, max_digits=17)),
            ],
        ),
    ]
